USE group_camp_query;

DROP TABLE IF EXISTS testing; 
CREATE TABLE testing(
	testing1 INT PRIMARY KEY NOT NULL, 
    testing2 VARCHAR(200) NOT NULL,
    testing3 DATETIME NOT NULL
)ENGINE INNODB;

DROP TABLE IF EXISTS camper;
CREATE TABLE camper(
	testing4 INT PRIMARY KEY NOT NULL, 
    testing5 VARCHAR(200) NOT NULL,
    testing6 DATETIME NOT NULL
)ENGINE INNODB;

DROP TABLE IF EXISTS cabin;
CREATE TABLE cabin(
	cabin_id INT PRIMARY KEY NOT NULL
    )ENGINE INNODB;
    
SELECT * FROM cabin;
SELECT * FROM camper;
SELECT * FROM testing;